from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

from harness import ROOT, decode_output


ROLES = (
    "business-analyst",
    "solution-architect",
    "readiness-reviewer",
    "developer",
    "code-reviewer",
    "test-engineer",
)
COMMANDS = ("harness-propose", "harness-apply", "harness-archive")
SKILLS = ("build-test", "post-verify", "systematic-debug", "code-review", "test-e2e")
SKILL_DESCRIPTIONS = {
    "build-test": "Discover and run repository-native compile, test, build, startup and smoke gates for Harness SA, Dev and TE work.",
    "post-verify": "Re-verify the actual diff against the baseline after implementation or test changes and record reproducible evidence.",
    "systematic-debug": "Diagnose reproducible build, test, runtime, environment, permission or Harness-tool failures without blind retries.",
    "code-review": "Perform independent read-only review of the current diff with requirement traceability, fixed checklists and deterministic ownership routing.",
    "test-e2e": "Execute independent Scenario-based end-to-end acceptance and regression testing with reproducible environment and evidence.",
}
LEGACY_SKILLS = ("dev-stack-verification", "orchestrate-harness-workflow")
GENERATED = "Generated by .harness/scripts/harness_init.py"
SHELL_ROLES = {"developer", "test-engineer"}


def python_command(platform: str | None = None) -> str:
    return "py -3" if (platform or os.name) == "nt" else "python3"


def opencode_plugin_version() -> str | None:
    executable = shutil.which("opencode")
    if not executable:
        return None
    try:
        completed = subprocess.run(
            [executable, "--version"],
            capture_output=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    output = decode_output(completed.stdout or completed.stderr)
    match = re.search(r"\b(\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?)\b", output)
    return match.group(1) if match else None


def write(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"WRITE {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def remove(path: Path, dry_run: bool) -> None:
    if not path.exists():
        return
    if dry_run:
        print(f"REMOVE {path.relative_to(ROOT)}")
        return
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()


def role_entry(role: str, platform: str) -> str:
    if platform == "opencode":
        bash_permission = "allow" if role in SHELL_ROLES else "deny"
        return f"""---
description: Harness {role} Worker. PM must invoke it through the platform Task tool.
mode: subagent
permission:
  read: allow
  glob: allow
  grep: allow
  edit: allow
  bash: {bash_permission}
  skill: allow
  task: deny
  harness_change: deny
  harness_git_read: deny
  harness_pm_write: deny
---

<!-- {GENERATED} -->
请读取并遵循 `.harness/subagents/{role}.md`。

handoff 使用 `TASK_NAME=<change-id>` 和 `TASK_ROOT=harness/specs/<change-id>` 标识任务。所有任务包产物名都相对 `TASK_ROOT` 解析；`.harness/` 只存放本体契约、模板、Skills、规则和脚本，禁止在其中查找任务包，也禁止使用 `.harness/specs/`。

你是真实独立 Worker，不得在 PM 主上下文中以角色扮演代替派发。
"""
    tools = "Read, Glob, Grep, Bash, Write, Edit" if role in SHELL_ROLES else "Read, Glob, Grep, Write, Edit"
    return f"""---
name: {role}
description: Harness {role} thin entry. Read .harness/subagents/{role}.md.
tools: {tools}
---

<!-- {GENERATED} -->
请读取并遵循 `.harness/subagents/{role}.md`。

handoff 使用 `TASK_NAME=<change-id>` 和 `TASK_ROOT=harness/specs/<change-id>` 标识任务。所有任务包产物名都相对 `TASK_ROOT` 解析；`.harness/` 只存放本体契约、模板、Skills、规则和脚本，禁止在其中查找任务包，也禁止使用 `.harness/specs/`。

你是真实独立 Worker，不得在 PM 主上下文中以角色扮演代替派发。
"""


def opencode_pm_entry() -> str:
    return f"""---
description: Harness workflow controller. Use only for Harness commands and delegate every BA/SA/RR/Dev/CR/TE stage through Task.
mode: primary
permission:
  read: allow
  glob: allow
  grep: allow
  list: allow
  edit: deny
  bash: deny
  harness_change: allow
  harness_git_read: allow
  harness_pm_write: allow
  skill: allow
  doom_loop: deny
  task: allow
---

<!-- {GENERATED} -->
你是 Harness PM，与 OpenCode 的 Build、Plan 同级。进入 Harness 命令后保持 PM 身份，直到用户手动切换 Primary Agent。

执行 Harness 命令时，先读取 `.harness/runtime.md`、`.harness/harness.yaml` 和对应 `.harness/commands/` 文件。

每个 BA、SA、RR、Dev、CR、TE 阶段都必须调用 OpenCode Task 工具，并指定对应的项目 SubAgent。禁止说“现在作为某角色”后在当前 PM 会话执行其工作；Task 不可用或被拒绝时返回 BLOCK，不能角色扮演降级。

阶段内必须自动推进：Dev/CR/TE 及其返工完成后立即进入唯一后继，不询问“是否继续”或“要我现在执行吗”。只有 propose → apply 与 apply → archive 停下等待用户；用户在失败后说“继续”只是恢复当前链路。

`git status`、`git diff` 不是阶段门禁。需要只读 Git 证据时调用 `harness_git_read`；同一转换中相同 action 与参数最多调用一次，成功空输出也算有效结果。工具无返回、失败或触发 doom-loop 时禁止原样重试，改用已有 Worker 产物、Return Contract、Read/Glob/Grep 或一次等价检查继续；确实缺少阻塞信息时只报告一次 DEGRADED。

不得直接执行 `mvn`、`gradle`、`npm`、`pnpm`、`yarn`、`pytest` 等项目构建/测试命令，它们属于 Dev/TE。OpenCode Task-after 的正常 delivery 只审计 Worker 本轮证据，不重放项目命令；当前 Worker 返回后只调用一次该角色的 `harness_change(action=delivery, ...)`，不得传 `--replay`。显式 `--replay` 仅用于人工诊断。禁止同一 change-id 并发 Dev/TE delivery；TE 早于最新 Dev/CR 时重走 CR/TE。

PM 的通用 Bash 与内置 edit 均被硬拒绝，不能依赖提示词维持所有权。生命周期只调用 `harness_change`，Git 只读只调用 `harness_git_read`；长期规格和记忆只通过 `harness_pm_write` 写入允许目录。非空记忆草稿必须先调用 `harness_change(action=memory-disposition, ...)` 明确 accepted/rejected/duplicate；随后归档调用 `harness_change(action=archive, ...)` 并检查四项 postconditions 与 memory_disposition，禁止再用 `Test-Path`、`test`、`Get-ChildItem` 或 `ls` 二次确认。

PM 只负责调度、门禁、看板、人工卡点、归档和索引。不得直接编辑 `harness/specs/<change-id>/` 中的 Worker 产物，不得修改业务源码或测试来代替 Developer。

非 Harness 请求不在 PM 中执行；提示用户切换到 Build 或 Plan。
"""


def command_entry(command: str, platform: str) -> str:
    routing = "agent: harness-pm\nsubtask: false\n" if platform == "opencode" else ""
    platform_note = (
        "OpenCode 中本命令切换到同级 `harness-pm` Primary Agent，并保持该 Agent，直到用户手动切换回 Build/Plan。"
        if platform == "opencode" else "Claude Code 在当前主会话作为 PM，通过项目级 Agent 工具派发六角色 Worker。"
    )
    return f"""---
description: Harness {command.removeprefix('harness-')} command
{routing}---

<!-- {GENERATED} -->
请先读取 `.harness/runtime.md`、`.harness/harness.yaml`，再读取并执行 `.harness/commands/{command}.md`。

本文件只是项目级薄入口，不复制 Harness 本体。{platform_note}
"""


def skill_entry(skill: str) -> str:
    return f"""---
name: {skill}
description: {SKILL_DESCRIPTIONS[skill]}
---

<!-- {GENERATED} -->
请读取并遵循 `.harness/skills/{skill}/SKILL.md`。
"""


def strip_harness_hooks(data: dict[str, object]) -> dict[str, object]:
    hooks = data.get("hooks")
    if not isinstance(hooks, dict):
        return data
    cleaned: dict[str, object] = {}
    for event, entries in hooks.items():
        if not isinstance(entries, list):
            cleaned[event] = entries
            continue
        kept = []
        for entry in entries:
            encoded = json.dumps(entry, ensure_ascii=False)
            if ".harness/scripts/" not in encoded and ".harness\\scripts\\" not in encoded:
                kept.append(entry)
        if kept:
            cleaned[event] = kept
    data["hooks"] = cleaned
    return data


def install_common(platform: str, dry_run: bool) -> None:
    base = ROOT / f".{platform}"
    for role in ROLES:
        write(base / "agents" / f"{role}.md", role_entry(role, platform), dry_run)
    for command in COMMANDS:
        write(base / "commands" / f"{command}.md", command_entry(command, platform), dry_run)
    if platform in {"claude", "opencode"}:
        for skill in SKILLS:
            write(base / "skills" / skill / "SKILL.md", skill_entry(skill), dry_run)
        for legacy in LEGACY_SKILLS:
            remove(base / "skills" / legacy, dry_run)


def install_claude(dry_run: bool) -> None:
    install_common("claude", dry_run)
    settings_path = ROOT / ".claude" / "settings.json"
    try:
        data = json.loads(settings_path.read_text(encoding="utf-8")) if settings_path.exists() else {}
    except json.JSONDecodeError as error:
        raise SystemExit(f"Cannot merge invalid .claude/settings.json: {error}")
    strip_harness_hooks(data)
    hooks = data.setdefault("hooks", {})
    command = python_command()
    role_matcher = "|".join(ROLES)
    existing_starts = hooks.get("SubagentStart", []) if isinstance(hooks.get("SubagentStart", []), list) else []
    hooks["SubagentStart"] = existing_starts + [{
        "matcher": role_matcher,
        "hooks": [{
            "type": "command",
            "command": f"{command} .harness/scripts/dispatch_subagent.py --platform claude --event start",
            "timeout": 30,
        }],
    }]
    existing_stops = hooks.get("SubagentStop", []) if isinstance(hooks.get("SubagentStop", []), list) else []
    hooks["SubagentStop"] = existing_stops + [
        {
            "matcher": role,
            "hooks": [{
                "type": "command",
                "command": f"{command} .harness/scripts/dispatch_subagent.py --platform claude --role {role}",
                "timeout": 660,
            }],
        }
        for role in ROLES
    ]
    write(settings_path, json.dumps(data, ensure_ascii=False, indent=2) + "\n", dry_run)


OPENCODE_PLUGIN = f"// {GENERATED}\n" + r'''import { tool } from "@opencode-ai/plugin";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHarnessHooksPlugin } from "../../.harness/adapters/opencode_pm.js";

const pluginDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(pluginDir, "..", "..");
export const HarnessHooksPlugin = createHarnessHooksPlugin(tool, root);
'''


def install_opencode(dry_run: bool) -> None:
    install_common("opencode", dry_run)
    package_path = ROOT / ".opencode" / "package.json"
    try:
        package_data = json.loads(package_path.read_text(encoding="utf-8")) if package_path.exists() else {}
    except json.JSONDecodeError as error:
        raise SystemExit(f"Cannot merge invalid .opencode/package.json: {error}")
    package_data["type"] = "module"
    dependencies = package_data.setdefault("dependencies", {})
    if isinstance(dependencies, dict):
        dependencies["@opencode-ai/plugin"] = (
            opencode_plugin_version()
            or str(dependencies.get("@opencode-ai/plugin") or "1.18.4")
        )
    else:
        raise SystemExit("Cannot merge .opencode/package.json: dependencies must be an object")
    write(package_path, json.dumps(package_data, ensure_ascii=False, indent=2) + "\n", dry_run)
    write(ROOT / ".opencode" / "agents" / "harness-pm.md", opencode_pm_entry(), dry_run)
    write(ROOT / ".opencode" / "plugins" / "harness-hooks.js", OPENCODE_PLUGIN, dry_run)


def install_trae(dry_run: bool) -> None:
    install_common("trae", dry_run)
    hooks_path = ROOT / ".trae" / "hooks.json"
    if not hooks_path.exists():
        return
    try:
        data = json.loads(hooks_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return
    strip_harness_hooks(data)
    if data.get("hooks"):
        write(hooks_path, json.dumps(data, ensure_ascii=False, indent=2) + "\n", dry_run)
    else:
        remove(hooks_path, dry_run)


def main() -> int:
    parser = argparse.ArgumentParser(description="Install project-local Harness adapters.")
    parser.add_argument("--tool", choices=("all", "claude", "opencode", "trae"), default="all")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    selected = ("claude", "opencode", "trae") if args.tool == "all" else (args.tool,)
    for platform in selected:
        {"claude": install_claude, "opencode": install_opencode, "trae": install_trae}[platform](args.dry_run)
    print("Harness adapters ready: " + ", ".join(selected))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
